network:
  host: 127.0.0.1
  port: 8090
  disable_auth: true
  disable_fetch_requests: true
logging:
  log_prompt: false
  log_generation_params: false
  log_requests: false
model:
  model_dir: ../../models
  model_name: qwen38-exl3-2.0
  backend: exllamav3
  max_seq_len: 16384
  cache_size: 16384
  cache_mode: Q8
  tensor_parallel: false
  vision: false
draft_model:
  draft_model_name:
